version: '3.1'

services:
    mysql:
        image: 'mysql:5.7'
        container_name: mysql
        restart: unless-stopped
        volumes:
            - '.:/public'
        environment:
            - MYSQL_ROOT_PASSWORD=toor
            - MYSQL_DATABASE=example
            - MYSQL_USER=user
            - MYSQL_PASSWORD=user
        ports:
            - '3306:3306'
        depends_on:
            - php-fpm
        networks:
            - app-network

    webserver:
        image: nginx
        volumes:
          - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
          - ./:/var/www/html
        ports:
        - "80:80"
        depends_on:
          - php-fpm
        networks:
          - app-network

    php-fpm:
        build: ./docker/php
        working_dir: /var/www/html/public
        volumes:
            - './:/var/www/html'
            - './docker/php/xdebug.ini:/etc/php/7.4/fpm/conf.d/xdebug.ini'
            - './docker/php/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
        environment:
          - PHP_IDE_CONFIG=serverName=Docker
        networks:
          - app-network

networks:
  app-network:
    driver: bridge
